### ISSUE TITLE
Mobile Zoom option

### ISSUE THREAD

**Issue by irfankhan6600** [Alamin02/khude-gobeshok-frontend#3]
**Bug: Mobile Zoom** 

whenever the page is zoomed in, the page became like this-

![viber_image_2019-10-28_16-42-50](https://user-images.githubusercontent.com/56947319/67672429-1ee73d80-f9a2-11e9-8960-18f231ea441a.jpg)

**Comment by Alamin02** [comment]
This issue is fixed hopefully. Please check.
